# Generated by Django 4.2.16 on 2026-01-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('warehouse_id', models.PositiveIntegerField()),
                ('location_id', models.PositiveIntegerField()),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], max_length=15)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_type', models.CharField(max_length=20)),
                ('reference_id', models.PositiveIntegerField()),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-movement_date'],
                'indexes': [models.Index(fields=['product_id', 'movement_date'], name='analytics_s_product_3d1c32_idx'), models.Index(fields=['warehouse_id', 'movement_date'], name='analytics_s_warehou_31fa73_idx'), models.Index(fields=['movement_type', 'movement_date'], name='analytics_s_movemen_e72978_idx')],
            },
        ),
    ]
